### ISSUE TITLE
Broken with current version of Homebrew?

### ISSUE THREAD

**Issue by michaelblyons** [danielbayley/homebrew-changelog#12]
```sh
$ brew changelog wget
Error: undefined method `formulae' for ["wget"]:Array
/usr/local/Homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/brew-changelog.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:113:in `<main>'
```

**Comment by Zifius** [comment]
+1

@danielbayley is the project alive?

**Comment by danielbayley** [comment]
> +1
> 
> @danielbayley is the project alive?

Yes! Sorry I will come back around to it…

**Comment by danielbayley** [comment]
@michaelblyons @Zifius I just pushed the refactoring I've been doing as and when… Should be much improved now! So feel free to test…

**Comment by Zifius** [comment]
Thanks @danielbayley, works again now!
