### ISSUE TITLE
Crashed :(

### ISSUE THREAD

**Issue by michaelblyons** [danielbayley/homebrew-changelog#17]
```
$ brew changelog wget
Error: uninitialized constant YAML
/usr/local/Homebrew/Library/Taps/danielbayley/homebrew-changelog/lib/utils.rb:61:in `<top (required)>'
/usr/local/Homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:8:in `require_relative'
/usr/local/Homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:8:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/usr/local/Homebrew/Library/Homebrew/commands.rb:77:in `external_ruby_v2_cmd_path'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by michaelblyons** [comment]
Side note: after trying to follow the `lib` reference on GitHub (online), basically every page in this repo crashes, too.

**Comment by michaelblyons** [comment]
Still getting the original error.

**Comment by Zifius** [comment]
I experience the same issue

**Comment by michaelblyons** [comment]
In _changelog.rb_,

1. Add `require "yaml"` at the top.
2. Remove `[String],` from `YAML.safe_load`.
3. Find all `.try\(:(\w+)\)` and replace with `&.\1`.

**Comment by michaelblyons** [comment]
Since #18 and #21 exist as well, I'm closing this three-year-old bug report as not-planned.
