### ISSUE TITLE
Bug: Error: undefined method `system_command' for module Homebrew

### ISSUE THREAD

**Issue by learn2reid** [danielbayley/homebrew-changelog#18]
```
brew changelog gh
Error: undefined method `system_command' for module Homebrew
/opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:92:in `block in changelog'
/opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:44:in `map'
/opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:44:in `changelog'
/opt/homebrew/Library/Homebrew/brew.rb:96:in `public_send'
/opt/homebrew/Library/Homebrew/brew.rb:96:in `<main>'
```

**Comment by learn2reid** [comment]
I did the fix of adding require yaml & the regex fix mentioned in another issue
